cv:
  name: ${CV_NAME}
  location: ${CV_LOCATION}
  email: ${CV_EMAIL}
  phone: ${CV_PHONE}
  birthday: ${CV_BIRTHDAY}
  website:
  social_networks:
  - network: LinkedIn
    username: nicola-perin
  - network: GitHub
    username: NicolaPerin

  sections:
    Profile:
        - >
          MSc graduate in Data Science and Scientific Computing

    Summary:
      - This is my CV managed with version control

    Education:
      - institution: Your University
        area: Your Field
        degree: Your Degree
        start_date: 2020-09
        end_date: 2024-05
        highlights:
          - Foundational training in theoretical and experimental physics

design:
  theme: moderncv
  header:
    photo_position: left
    photo_width: 3cm

