cv:
  name: ${CV_NAME}
  location: ${CV_LOCATION}
  email: ${CV_EMAIL}
  phone: ${CV_PHONE}
  birthday: ${CV_BIRTHDAY}
  website:
  social_networks:
    - network: LinkedIn
      username: nicola-perin
    - network: GitHub
      username: NicolaPerin
  sections: {}

design:
  theme: moderncv
  page:
    size: a4
    top_margin: 1.3cm
    bottom_margin: 1.3cm
    left_margin: 1.3cm
    right_margin: 1.3cm
    show_footer: false
    show_top_note: false
  colors:
    body: rgb(0, 0, 0)
    name: rgb(0, 79, 144)
    connections: rgb(0, 79, 144)
    section_titles: rgb(0, 79, 144)
    links: rgb(0, 79, 144)
  typography:
    font_family:
      body: Helvetica
      name: Helvetica
      section_titles: Helvetica
      connections: Fontin
    font_size:
      body: 10pt
      name: 25pt
      section_titles: 1.3em
    line_spacing: 0.6em
    alignment: justified
    date_and_location_column_alignment: right
    bold:
      name: false
      section_titles: false
    small_caps:
      name: false
      section_titles: false
  links:
    underline: true
    show_external_link_icon: false
  header:
    alignment: left
    photo_width: 3cm
    space_below_name: 0.4cm
    space_below_connections: 0.7cm
    space_between_connections: 0.5cm
    connections:
      separator: ''
      show_icons: true
      hyperlink: true
      display_urls_instead_of_usernames: false
      phone_number_format: international
  section_titles:
    type: moderncv
    line_thickness: 0.15cm
    space_above: 0.5cm
    space_below: 0.3cm
  entries:
    date_and_location_width: 2.6cm
    side_space: 0cm
    space_between_columns: 0.4cm
    allow_page_break: true
    short_second_row: false
    highlights:
      bullet: "•"
      nested_bullet: "-"
      space_above: 0.25cm
      space_left: 0cm
      space_between_items: 0.19cm
      space_between_bullet_and_text: 0.3em
    summary:
      space_left: 0cm
  sections:
    space_between_regular_entries: 0.3cm
    allow_page_break: true
    show_time_spans_in: []
  templates:
    one_line_entry:
      main_column: "**LABEL:** DETAILS"
    education_entry:
      main_column: |-
        **INSTITUTION**, DEGREE AREA -- LOCATION
        SUMMARY
        HIGHLIGHTS
      date_and_location_column: DATE
    normal_entry:
      main_column: |-
        **NAME** -- **LOCATION**
        SUMMARY
        HIGHLIGHTS
      date_and_location_column: DATE
    experience_entry:
      main_column: |-
        **POSITION**, COMPANY -- LOCATION
        SUMMARY
        HIGHLIGHTS
      date_and_location_column: DATE
    publication_entry:
      main_column: |-
        **TITLE**
        SUMMARY
        AUTHORS
        URL (JOURNAL)
      date_and_location_column: DATE

settings:
  render_command:
    dont_generate_markdown: false
    dont_generate_html: false
    dont_generate_png: false