cv:
  name: ${CV_NAME}
  location: ${CV_LOCATION}
  email: ${CV_EMAIL}
  phone: ${CV_PHONE}
  birthday: ${CV_BIRTHDAY}
  website:
  social_networks:
  - network: LinkedIn
    username: nicola-perin
  - network: GitHub
    username: NicolaPerin

  sections:
    Profile:
        - >
          MSc graduate in Data Science and Scientific Computing

    Summary:
      - This is my CV managed with version control

    Education:
      - institution: Your University
        area: Your Field
        degree: Your Degree
        start_date: 2020-09
        end_date: 2024-05
        highlights:
          - Foundational training in theoretical and experimental physics

design:
  theme: moderncv
  page:
    size: a4
    top_margin: 1.3cm
    bottom_margin: 1.3cm
    left_margin: 1.3cm
    right_margin: 1.3cm
    show_page_numbering: false
    show_last_updated_date: false
  colors:
    text: rgb(0, 0, 0)
    name: rgb(0, 79, 144)
    connections: rgb(0, 79, 144)
    section_titles: rgb(0, 79, 144)
    links: rgb(0, 79, 144)
    last_updated_date_and_page_numbering: rgb(128, 128, 128)
  text:
    font_family: Helvetica
    font_size: 10pt
    leading: 0.6em
    alignment: justified
    date_and_location_column_alignment: right
  links:
    underline: true
    use_external_link_icon: false
  header:
    name_font_family: Helvetica
    name_font_size: 25pt
    name_bold: false
    small_caps_for_name: false
    photo_width: 3cm
    vertical_space_between_name_and_connections: 0.4cm
    vertical_space_between_connections_and_first_section: 0.7cm
    horizontal_space_between_connections: 0.5cm
    connections_font_family: Fontin
    separator_between_connections: ''
    use_icons_for_connections: true
    use_urls_as_placeholders_for_connections: false
    make_connections_links: true
    alignment: left
  section_titles:
    type: moderncv
    font_family: Helvetica
    font_size: 1.3em
    bold: false
    small_caps: false
    line_thickness: 0.15cm
    vertical_space_above: 0.5cm
    vertical_space_below: 0.3cm
  entries:
    date_and_location_width: 2.6cm
    left_and_right_margin: 0cm
    horizontal_space_between_columns: 0.4cm
    vertical_space_between_entries: 0.3cm
    allow_page_break_in_sections: true
    allow_page_break_in_entries: true
    short_second_row: false
    show_time_spans_in: []
  highlights:
    bullet: "•"
    nested_bullet: "-"
    top_margin: 0.25cm
    left_margin: 0cm
    vertical_space_between_highlights: 0.19cm
    horizontal_space_between_bullet_and_highlight: 0.3em
    summary_left_margin: 0cm
  entry_types:
    one_line_entry:
      template: "**LABEL:** DETAILS"
    education_entry:
      main_column_first_row_template: "**INSTITUTION**, DEGREE AREA -- LOCATION"
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: DATE
    normal_entry:
      main_column_first_row_template: "**NAME** -- **LOCATION**"
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: DATE
    experience_entry:
      main_column_first_row_template: "**POSITION**, COMPANY -- LOCATION"
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: DATE
    publication_entry:
      main_column_first_row_template: "**TITLE**"
      main_column_second_row_template: |-
        AUTHORS
        URL (JOURNAL)
      main_column_second_row_without_journal_template: |-
        AUTHORS
        URL
      main_column_second_row_without_url_template: |-
        AUTHORS
        JOURNAL
      date_and_location_column_template: DATE
